version: 2

sources:
  - name: bronze
    database: "{{ env_var('DBT_SOURCE_DATABASE', target.database) }}"
    schema: BRONZE  # Change to BRONZE if seeds are loaded into BRONZE
    tables:
      - name: bronze_customers
      - name: bronze_orders
      - name: bronze_products
      - name: bronze_orderitems